### ISSUE TITLE
Nice

### ISSUE THREAD

**Issue by pumpan** [angoyd/freshintelliventHacs#21]
Im realy rooting for this project!
Do you have a forum post for this in the official forum?  Im struggeling to get it to work atm with this in the logs 

`custom_components.fresh_intellivent_sky.config_flow
Source: custom_components/fresh_intellivent_sky/config_flow.py:152 
Integration: fresh_intellivent_sky ([documentation](https://github.com/angoyd/freshintelliventHacs), [issues](https://github.com/angoyd/freshintelliventHacs/issues)) 
First occurred: 20 januari 2023 20:01:24 (1 occurrences) 
Last logged: 20 januari 2023 20:01:24

Error connecting to and getting data from 4C:96:2D:1B:26:BE: 4C:96:2D:1B:26:BE - 4C:96:2D:1B:26:BE: Failed to connect: failed to discover services, device disconnected `

The Mac is the intellivent.. any ideas?

**Comment by angoyd** [comment]
Hi,

We have a Discord to so the initial communication https://discord.gg/tK4Gac6j

You are welcome to join

/Anders
