### ISSUE TITLE
No devices found?

### ISSUE THREAD

**Issue by KlasFNilsson** [angoyd/freshintelliventHacs#32]
Would love to get this working! But when adding integration (after adding in HACS) in directly says ”No devices found”. It doesn’t seem to search at all. Shouldn’t it at least wait a few seconds before giving up?

My Bluetooth (Raspberry PI 4 built in) works with other BLE devices.
I’ve tried searching with and without putting the fan in pairing mode (pressing for 8s until starts blinking).
The fan is connected to my iPhone app.
I’ve moved the Raspberry PI to within a few meters. The iPhone has no problem with range.

**Comment by KlasFNilsson** [comment]
After a day of testing suddenly (manually readded the files, and did a few reboots for other reasons) I get another message - but won’t work….
Now I get ”Please wait, starting configuration wizard for Fresh Intellivent Sky”, but after a minute it goes to ”Couldn’t connect”. Even if I set the fan into pairing mode….

**Comment by angoyd** [comment]
Hi, have you enabled debug logging for the component, to see if we get any error messages from that? The range of the fans seams to be pretty short, so one way might be to try to move the PI closer to the fan and se if its found.

**Comment by tedenda** [comment]
Adding a Bluetooth proxy can also be an option worth trying.

**Comment by KlasFNilsson** [comment]
Thank you! I will try to fix the signal strength first. Didn’t know about the Bluetooth proxy, and I’m eager to test!  I’ll get back to you here with results! Thanks again!

**Comment by KlasFNilsson** [comment]
Already tested a Bluetooth proxy. Worked like a charm! It was definitely a problem with Bluetooth interference on the Raspberry PI 4, even with an external Bluetooth dongle with (a short) USB extension chord!
Case closed. Integration excellent! Thank you!
