### ISSUE TITLE
Raw Mode 35 is Unknown

### ISSUE THREAD

**Issue by FlyHigh-Swe** [angoyd/freshintelliventHacs#33]
When I start the timer ventilation (forced) the Raw mode shows 35 and the Mode is "Unknown". 
If the fan runs at constant speed it shows Raw mode 16 and Mode "Constant speed" and Raw mode 34 is "Light" (as expected) 

I also noticed I can set the timer and light variables individual in the app while it shares speed in HomeAssistant. 
Maybe a firmware thing where the separated or combined the modes? 

Intellivent sky info: 
Firmware: 01.05
Hardware: 01.02

**Comment by LaStrada** [comment]
> I also noticed I can set the timer and light variables individual in the app while it shares speed in HomeAssistant.

They share the same values in the app as well. It might look like they don't because of some issues in the app you can get some "random" values right after changing it. But if you restart the app after changing one of the values, you will see both of them have the same value. This was also verified by sniffing the BLE traffic.

**Comment by LaStrada** [comment]
Never seen 35 in my setup. But I've seen 57 and 69. I have all the logs and values, so I might need to look into that.

Would've been nice to know exactly what the sensor values was reporting when you got 35. It's easier to debug when all the different modes have different RPM (if possible).

This ticket should probably live here:
https://github.com/LaStrada/pyfreshintellivent
This repository only uses values from this framework.

**Comment by FlyHigh-Swe** [comment]
> Never seen 35 in my setup. But I've seen 57 and 69. I have all the logs and values, so I might need to look into that.
> 
> Would've been nice to know exactly what the sensor values was reporting when you got 35. It's easier to debug when all the different modes have different RPM (if possible).
> 
> This ticket should probably live here: https://github.com/LaStrada/pyfreshintellivent This repository only uses values from this framework.

For me mode 35 is timer, I just tested activating the timer (without turning on lights, I have a separate button for forced ventilation from the old fan). It also shows as timer in the app.

Mode 34 is light (also confirmed with app).

And you are correct about the speeds. It felt as I could set the timer and light to different speeds but when I try it again it is as you described. 

Its a tiny issue. I can still see why the fan starts in most cases and I know unknown is the same as timer. so far thats the only mode that is unknown.

**Comment by LaStrada** [comment]
Yeah, I was looking into the code now. I have really never tested timer. Will do some testing the next few days and I'll try to fix the missing modes. Thanks for the feedback!

**Comment by LaStrada** [comment]
A new version of the framework (`0.3.0`) is now available. Will bump the version in this repo after a bit more testing.
