### ISSUE TITLE
Fresh Intellivent ICE support

### ISSUE THREAD

**Issue by AngelVenchev** [angoyd/freshintelliventHacs#42]
I bought 2 Fresh Intellivent ICEs for my bathrooms. I wanted to know if there's any chance they would be supported in the future?

I am a software developer myself, but haven't built anything like this before. If you point me in the right direction I'd be happy to help on this. 

I am guessing I have to do some sort of discovery of what happens in the Bluetooth communication and then afterwards plug into that and send/receive info between HA and the device. 

Right now with the current integration I am unable to find the ICE device. It's in discovery mode but HA doesn't see it throught the integration's UI setup

**Comment by tedenda** [comment]
Hello,

I am happy that you want to help develop support for new models from Fresh.

This repo is the Hacs implementation using this library:
https://github.com/LaStrada/pyfreshintellivent

I am not a python developer but have helped with some other parts like documentation, logo and testing.

**Comment by angoyd** [comment]
Hi,

As Daniel said, this component is using the library from LaStrada, and Fresh is not willing to share their bluetooth protocol så we have had to make reverse engineering to make the library, but you can contact Lastrada and see if he has some tips how to do that for the ICE model

**Comment by tedenda** [comment]
@AngelVenchev Create this issue over there and hopefully we can get support sorted out. Hopefully the interface is not totally new from what's currently in place.

Regarding Fresh, maybe it's time to make a new try to ask them. I have contacted them earlier about their iPhone app with some degree of success. Can make a try...
