### ISSUE TITLE
Change type/format on mode sensor?

### ISSUE THREAD

**Issue by tedenda** [angoyd/freshintelliventHacs#9]
When checking the History in Home Assistant the mode sensor is shown like this:

![fis_mode_sensor](https://user-images.githubusercontent.com/4216986/208240153-b2d9a200-3bb7-470b-bbe9-49adeeaf1f66.jpg)

But I think this is better:

![FIS_Mode_State](https://user-images.githubusercontent.com/4216986/208239923-eed4ec38-3662-4f26-a98b-741cdaf77fdd.jpg)

**Comment by LaStrada** [comment]
Maybe this PR #23  will fix this?

**Comment by tedenda** [comment]
Maybe!

**Comment by tedenda** [comment]
This works now in 0.2.0rc3

![image](https://user-images.githubusercontent.com/4216986/215875346-f54f2c71-0e8f-418e-a7f6-5c395a56c5ca.jpeg)
